language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.1

script: 'bundle exec rake test'

notifications:
  email:
    recipients:
      - sclarkdev@gmail.com
    on_failure: change
    on_success: never
